companieshouse/confirmation-statement-api

pom.xml
src/main/java/uk/gov/companieshouse/confirmationstatementapi/contoller/ConfirmationStatementController.java

Clean up the pom file

---

Tiltfile.dev
pom.xml
src/main/java/uk/gov/companieshouse/confirmationstatementapi/contoller/ConfirmationStatementController.java

Add docker file to the project.

Add docker files to project

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/ApiClientService.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/TransactionInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/TransactionService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/TransactionInterceptorTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/TransactionServiceTest.java

Api Key does not have the priveledges to retrieve a transaction. Using OAuth authenticated Api Client to retrieve Transaction instead

Switch from API key to Oauth token api client

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/contoller/ConfirmationStatementController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/TransactionInterceptor.java

Also retrieve transaction from using Request Attribute not Model Attribute

Add transaction related debug logs

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/configuration/ConfirmationStatementServiceEligibilityConfig.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/EligibilityFailureReason.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyTypeValidationPaperOnly.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyTypeValidationPaperOnlyTest.java

https://companieshouse.atlassian.net/browse/NCS-209
Validation for Paper only filing Company types

NCS 209 company type validation paper only

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/configuration/ConfirmationStatementServiceEligibilityConfig.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/EligibilityFailureReason.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyTypeValidationForWebFiling.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyTypeValidationForWebFilingTest.java

[NCS-208](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=186&modal=detail&selectedIssue=NCS-208)
Add a company type validation class to check whether a company can use web-filing to file a CS01. Also contains unit tests and configs.

NCS-208 add company type validation for web-filing

---

src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/TransactionInterceptorTest.java

Unit test coverage missing in TrasnactionInterceptor catch block.

Transaction interceptor unit test coverage

---

service-map.json

NCS-307 Neo 4j json

---

spec/schema.json

Updating the api spec for create endpoint to use the existing ConfirmationStatementCreated type

NCS-310 Updating spec create endpoint for return type

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidation.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidationTest.java

stop null pointer from being thrown trying to loop through null officers list

fix null pointer due to 0 officer company

---

src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/CompanyProfileServiceTest.java

Test for company not found exception

Company profile api test coverage

---

pom.xml

update jib maven plugin version to resolve api build failures

update jib maven plugin version to resolve api build failures

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClient.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/contoller/ConfirmationStatementController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/contoller/StatementOfCapitalController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/exception/ServiceException.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/StatementOfCapital.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/StatementOfCapitalService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClientTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/contoller/ConfirmationStatementControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/contoller/StatementOfCapitalControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/StatementOfCapitalServiceTest.java

Added oracle query api call for statement of capital to the cofirmation statement api.

Ncs 469 endpoint for statement of capital

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/contoller/StatementOfCapitalController.java

NCS 457 Remove transaction from endpoint url

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/StatementOfCapital.java

Similar to NCS-491 updated the model to match the changes in the oracle query api.

NCS-492 Updated soc model

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/configuration/InterceptorConfig.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/LoggingInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/UserAuthInterceptor.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/UserAuthInterceptorTest.java

Prevent users from sending requests that interact with transactions they did not create

Ncs 463 user authentication

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/UserAuthInterceptor.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/UserAuthInterceptorTest.java

The story AC specifies there will be a response body. So adding a response body

Set response body when user not authed

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/ConfirmationStatementController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/controller/ConfirmationStatementControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

Endpoint to allow retrieval of an existing submission

Ncs 479 get submission endpoint

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidation.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidationTest.java

[NCS-452
](https://companieshouse.atlassian.net/browse/NCS-452)
Update the officers validation to return false when 0 officers is present. It initially returned true in this case.

NCS-452 Update officers validation

---

spec/schema.json

Could not find any reference to the transaction id, but did remove the full object from the 404 response.

Swagger spec for statement of capital updated

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/OfficerController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/ActiveOfficerDetails.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/contoller/OfficerControllerTest.java

Change dob from Date to string.

Update active officer details dob

---

src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

A few fixes highlighted by IntelliJ for a few unit tests

NCS-477 Typo fixes and IntelliJ highlighted fixes in a few unit tests

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/siccode/SicCodeDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/siccode/SicCodeDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/siccode/SicCodeDataJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/siccode/SicCodeJson.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java

[NCS-360](https://companieshouse.atlassian.net/browse/NCS-360)
Save sic code status to the database and make it available for cs web.

Ncs 360 add sic code model to cs submission

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClient.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/PersonOfSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/PscService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClientTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/PscServiceTest.java

map the PSC data from the oracle-query-api into the CHS api psc model

NCS-532 add psc mapping into CHS api style classes

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java

There were some issues when using real data, date format was different and some data was null causing some null pointer errors.

NCS-532 Fixing get pscs null pointer issues and fixed unit test

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/activedirectordetails/ActiveDirectorDetailsDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/activedirectordetails/ActiveDirectorDetailsDataJson.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java

save active director section status

save active director section status

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClient.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/ShareholderController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/shareholder/ShareholderJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ShareholderService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClientTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/controller/ShareholderJsonControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ShareholderServiceTest.java

[NCS-509](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=NCS&modal=detail&selectedIssue=NCS-509)
Add shareholder endpoint to the confirmation statement api

Ncs 509 shareholder endpoint api

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/ActiveDirectorDetails.java

[NCS-602](https://companieshouse.atlassian.net/browse/NCS-602): Update to retrieve full correspondence address
[NCS-621](https://companieshouse.atlassian.net/browse/NCS-621):  Update to retrieve full usual residential address

Retrieve active director details' full addresses

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/shareholder/ShareholderDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/shareholder/ShareholderDataJson.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java

[NCS-281](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-281)
Add mapping and shareholder status model

NCS-281 Add shareholder status model and mapping

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClient.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/payment/ConfirmationStatementPaymentJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClientTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

Call oracle query api to get a flag to say whether the confirmation statement is paid for a given period for that company. If true we do not add a costs link to the transaction, if it is false we add this second link.

Ncs 632 costs link

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/PersonOfSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java

Adding ISO format Date of birth to the PSC data
Removed country_of_residence as we are already inheriting it from the parent class.

NCS-325 Adding date of birth iso to psc mapping

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/ConfirmationStatementController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/exception/SubmissionNotFoundException.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/controller/ConfirmationStatementControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

Checks each field to ensure that they are present and that they have the correct status value.
Asked analyst and we will be including recent filing.

Ncs 656 validation status endpoint

---

spec/schema.json

Adding the next-made-up-to-date endpoint into the schema spec

NCS-242 Updating schema for next-made-up-to-date endpoint

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/configuration/ConfirmationStatementServiceEligibilityConfig.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/registerlocation/RegisterLocationsDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/registerlocation/RegisterLocationsDataJson.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java

save register locations section status

NCS-283 - save register locations section status

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

Register location has now been added for other tickets so integrating this into the validation sttaus checks.

NCS-625 Ensure that register location is included

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/TradingStatusDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/TradingStatusDataJson.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java

[NCS-345](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-345)
Save trading status answer to the cs submission database.

NCS-345 save trading status answer

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java

[NCS-345](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=NCS&modal=detail&selectedIssue=NCS-345)
Amend field and property name

NCS-345 Save trading status answer 

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/TradingStatusDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/TradingStatusDataJson.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/JsonDaoMappingTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/MockConfirmationStatementSubmissionData.java

[NCS-689](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-689)
Use boolean fields in trading status data instead of section section status.

NCS-689 Amend trading status data

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/PersonOfSignificantControl.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/PersonOfSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java

ncs-323 - add full address to psc model

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/PersonOfSignificantControl.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/PersonOfSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java

include housenamenumber in psc service address

ncs-323 - include housenamenumber in psc service address

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/PersonOfSignificantControl.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/PersonOfSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java

[NCS-619](https://companieshouse.atlassian.net/secure/RapidBoard.jspa?rapidView=234&projectKey=BI&modal=detail&selectedIssue=NCS-619)
Add mapping to the psc register location field

NCS-619 Add mapping for register location field

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/ActiveDirectorDetails.java

include officer country of residence

ncs-724 - include officer country of residence

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/OfficerController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/OfficerService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/controller/OfficerControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/OfficerServiceTest.java

[NCS-761](https://companieshouse.atlassian.net/browse/NCS-761)
Added confirmation statement submission check for officers details so that the endpoint user needs to add a valid confirmation statement submission id to retrieve the data.

Ncs 761 rename endpoints

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/ConfirmationStatementSubmissionDataDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/ConfirmationStatementSubmissionDataJson.java

Bug causes cs-web not to save/map the active officer details submission data.

BugFix: Update activeOfficerDetails data json mapping

---

README.md
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/CostsController.java

changing confirmation-statement-id to confirmation_statement_id in costs endpoint

Bug fix to correct costs endpoint param name

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/SubmissionInterceptor.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/SubmissionInterceptorTest.java

[NCS-761](https://companieshouse.atlassian.net/browse/NCS-761)
Check transaction id so that data is only returned if it correlates with the submission id.

NCS-761 Check transaction id

---

spec/schema.json
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/ActiveOfficerDetails.java

Add corporate identifier fields to ActiveOfficerDetails.

BI-9482 Retrieve corporate Active Officer Details.

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClient.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/OfficerController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/OfficerService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClientTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/controller/OfficerControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/OfficerServiceTest.java

Implement endpoint for multiple officers

BI-9487 - Implement endpoint for multiple officers

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidation.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidationTest.java

Added test to check compaies with zero ofiicers and throw the same exception as companies with more than five.

BI-9787 exclude companies with zero officers from passing eligibility

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/PersonOfSignificantControl.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/dao/personsignificantcontrol/PersonSignificantControlDao.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/PersonOfSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/json/personsignificantcontrol/PersonSignificantControlJson.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapper.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/model/mapping/PscsMapperTest.java

Updated 4 model classes
PersonOfSignificantControl
PersonOfSignificantControlDao and
2 PersonOfSignificantControlJson classes
Updated the mapper and the unit test.

BI-10106 Added usual residential country to psc models

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/configuration/ConfirmationStatementServiceEligibilityConfig.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidation.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/eligibility/impl/CompanyOfficerValidationTest.java

Removed the flag and related code and unit tests.

BI-10467 remove officer validation feature flag check

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/configuration/InterceptorConfig.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/NextMadeUpToDateController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/CompanyNumberValidationInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/SubmissionIdValidationInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/TransactionIdValidationInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/utils/Constants.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/CompanyNumberValidationInterceptorTest.java

Update for path-varaible name required for next made up to date as the name needs to be consistent for path validation.
Checked node sdk calls and it should not affect the web calls for this endpoint.

BI-10599 Validate Company Number for eligibility and next made up to

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/SubmissionInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/SubmissionIdValidationInterceptor.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/SubmissionInterceptorTest.java

1) Escape characters in submission interceptor
2) Concat suffix to indicate a string has been truncated.

BI-10801 Escape submission id that are less 50 characters long

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/CompanyNumberValidationInterceptor.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/interceptor/validation/TransactionIdValidationInterceptor.java

Elipses missing on long company numbers and transaction ids.

BI-10830 Show Ellipses on all long ids and numbers

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClient.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/controller/EmailController.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/exception/RegisteredEmailNotFoundException.java
src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/EmailService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/client/OracleQueryClientTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/controller/EmailControllerTest.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/EmailServiceTest.java

Fix for no corporate body detail record or empty email address to return 404

Ecct 165 enhance confirmation statement service for rea

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/FilingService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/FilingServiceTest.java

- Modified getFilings endpoint to includ REA in the data (map) for an INITIAL_FILING
- Updated the JUnit tests
- Tested all AC in my local CHS Dev Env and pass OK

ecct-742-get-filings-with-rea

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

Fixed need for email to be provided with initial filing to gain a valid statement, JUnit tests updated, AC re-tested as passing in the CHS Dev Env.

ecct-843-fix-initial-filing-needs-email

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

- The validation has been updated to check the statement flag
- The JUnit tests updated
- All AC have been verified as passing in the local CHS Dev Env

ecct-801-validate_accept-lawful-purpose-statement

---

pom.xml
src/test/java/uk/gov/companieshouse/confirmationstatementapi/configuration/InterceptorConfigRouteMatchingTest.java

- Updated maven versions for dependabot
- Updated a JUnit test
- Smoke tested in CHS Dev Env as still working OK

updated maven versions for dependabot

---

src/main/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementService.java
src/test/java/uk/gov/companieshouse/confirmationstatementapi/service/ConfirmationStatementServiceTest.java

Also added a comment explaining date flag value, and tightened up some unit tests that I noticed were unreliable when experimenting with an alternative way to make this change.

Update default value for ECCT date flag [ECCT-880]

---

Makefile

fix makeFile indentations

---

terraform/groups/ecs-service/locals.tf

Adding healthcheck path to load balancer listener rules

feat: add healthcheck to listener paths

---

README.md
pom.xml
terraform/groups/ecs-service/locals.tf

https://companieshouse.atlassian.net/browse/JU-885
update springboot version & other dependencies
remove healthcheck from lb path

Tech debt - 885

---

terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf

JU-885: tech debt for confirmation statement api
